### ISSUE TITLE
Error on any completion

### ISSUE THREAD

**Issue by fullpipe** [kristijanhusak/deoplete-phpactor#7]
NVIM v0.3.1
```
Error from phpactor: JSONDecodeError('Expecting value: line 1 column 1 (char 0)').  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "~/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 179, in _gather_results
    result = self._get_result(context, source)
  File "~/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 234, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "~/.config/nvim/plugged/deoplete-phpactor/rplugin/python3/deoplete/source/phpactor.py", line 65, in gather_candidates
    result = json.loads(result.decode())
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kristijanhusak** [comment]
Please post output of `phpactor#Status()`

**Comment by fullpipe** [comment]
That helped. phpactor#Status() said than phpactor does not installed. Installing it via `composer global require phpactor/phpactor` solved the problem.
